language: php

php:
  - 5.3
  - 5.4

before_script:
  - git clone https://github.com/AOP-PHP/AOP
  - sh -c "cd AOP && phpize && ./configure && make && sudo make install"
  - echo "extension=aop.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
 
script:
  - cd tests
  - phpunit --bootstrap bootstrap.travis.php .
